module.exports = {
  PASSWORD: 'PA$$WORD1235',
  MAX_EMAIL_CHECK_ATTEMPTS: 5,
  EMAIL_CHECK_INTERVAL_MS: 5000,
  OUTPUT_FILE_PATH: 'generated/accounts.json',
  CONCURRENT_LIMIT: 50,
  MAX_ACCOUNTS: 1000,
}
