name: Keep MEGA Accounts Active

on:
  schedule:
    - cron: '0 0 */15 * *'  # Runs every 15 days at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep_active:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create accounts directory
        run: mkdir -p generated

      - name: Create accounts.json if not exists
        run: |
          if [ ! -f generated/accounts.json ]; then
            echo '[]' > generated/accounts.json
          fi

      - name: Run keep-active command
        run: ./bin/fdrive accounts keep-active

      - name: List accounts status
        run: ./bin/fdrive accounts list

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add generated/accounts.json
          git commit -m "Update accounts status" || echo "No changes to commit"
          git push
